### ISSUE TITLE
HELP I Still Dont Understand This Math

### ISSUE THREAD

**Issue by Tich1212** [USACE/go-consequences#36]
@HenryGeorgist 
@Brennan1994 
https://github.com/USACE/go-consequences/blob/587076c011864c08b8cef383200a2e14e537c084/crops/crop.go#L121-L132

**Comment by Brennan1994** [comment]
Why percentProductionValue * totalMarketValueLessHarvestCost? Why not totalMarketValueLessHarvest cost + exposedProductionValue?

**Comment by HenryGeorgist** [comment]
We are trying to allocate the remainder between production cost (without harvest) and market value (without harvest) ~ which roughly equals profit. across the entire production timeframe..

**Comment by Brennan1994** [comment]
This is an instance where I wish we were all still in the office with a whiteboard available to talk around. I'm not sure I'm following what you're saying here.  multiplying total market value by damage factor makes sense. We have the market value of the crop, but we lose 75% of the crops to flooding, so we lose 75% of that market value.   

The other factor here is that we've lost all the work we've put in to those crops that got flooded, and we need to account for that. I'd suspect we'd increase our losses by whatever we spent producing them (exposedProductionValue). Instead we're multiplying that 75% loss by another factor that's relating exposed production value to total production cost. (how much money we'd put into producing that crop before it flooded, divided by how much money it would have taken to raise that crop to fruition without a flood.) and I don't think that's accomplishing the same thing I was describing. 

I'm missing something here. Either in the definitions of these terms, or conceptually what this loss is.

**Comment by HenryGeorgist** [comment]
Closing comment - moving to discussion board. https://github.com/USACE/go-consequences/discussions/38
