### ISSUE TITLE
Write an abstract compute using the FIPS code to iterate over structures rather than BBOX

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/go-consequences#44]
**Is your feature request related to a problem? Please describe.**
If a stakeholder wants to compute by county or state, the bounding box compute will possibly compute, and report structures outside of that boundary. creating a compute by state may provide greater flexibility in application of the tool

**Describe the solution you'd like**
Something like StreamAbstract, but the iteration will need to change because the structure provider will provide the iteration unit.

**Describe alternatives you've considered**
This is a special use case probably. Probably needs to be optimized for a national compute that is done concurrently.

**Comment by sacohen11** [comment]
I think this would be useful to go-fathom. I was working on re-factoring and noticed there was a BBox dependency which I need to work around. A StreamAbstract by FIPS would work around this.

**Comment by HenryGeorgist** [comment]
Ready for Testing under commit# b75dafca445

**Comment by HenryGeorgist** [comment]
Does provide hazard by geographic location work for you in go-fathom? I think it was using FD_ID previously, which would require a bit more refactoring.

**Comment by sacohen11** [comment]
@HenryGeorgist It does use FD_ID. I will go in and update the provide hazard function to get rid of the fd_id.

**Comment by HenryGeorgist** [comment]
@sacohen11 that should work. there may be multiple structures at the same xy, but they will receive the same depth for the events. The compute method for the consequences receptor will take into account the variation in the attribution of the structures.

**Comment by HenryGeorgist** [comment]
I tested this and it has worked for me.
