### ISSUE TITLE
Review Damage Function Sources for NACCS and FEMA coastal functions

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/go-consequences#89]
The damage function sources for wave, salinity and other coastal drivers need to be reviewed for accuracy. Check on the erosion branch.

https://github.com/USACE/go-consequences/blob/erosion/structures/occupancytypes.go

**Comment by rnugent3** [comment]
All the coastal sources looked good to me. 

Is the 3-story no/with basement EGM? I am tracking that the EGM has 1 story, 2 or more stories, and split level. 

Does documentation exist on the Galveston functions?

**Comment by HenryGeorgist** [comment]
3 story no basement should not be EGM thanks for the catch. I don't know if further documentation on the Galveston curves exist, i also need to verify that is the source from the old HEC-FIA functions.

I also need to fix some issues where medium and high wave may not be fully marshaling and unmarshaling correctly.
