### ISSUE TITLE
add ability to compute aggregated stage damage functions

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/go-consequences#95]
to support HEC-FDA, we need the ability to compute aggregated stage damage functions.

The inputs to the aggregated stage damage function will simply be a series of hydraulic data providers, an aggregation location, and a structure provider.

the output will be a x values of elevation, and an inline histogram for each x value representing damages.

**Comment by Brennan1994** [comment]
Test dataset here: https://drive.hecdev.net/share/pi6ztii8

**Comment by HenryGeorgist** [comment]
gratzi
