### ISSUE TITLE
Create a Factory for Structure Providers

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/go-consequences#99]
Currently there is not much structure to creating a structure provider. Developing a generalized structure provider factory will improve the accessability and simplicity of building the right type of structure provider at runtime.

A structure provider factory should have a simple configuration injected that is used to determine the right type of structure provider. The configuration would likely have a file path to the structure local resources (if applicable) and a file path to the occupancy type provider (if applicable). the options are currently shapefile, geopackage, and nsi api (which should be the default case). Determine between shapefile and gpkg based on the extension of the file path (if provided).

**Comment by trietmnj** [comment]
Merged in #101
